config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :conversations, only: [:index, :show]
  get 'search/:id' => 'posts#search', as: :search
  get 'create_post/:id' => 'conversations#create_post', as: :create_post
  get 'clip-support-page' => 'posts#clip_support_page', as: :clip_support_page
  get 'clip-tag' => 'posts#clip_tag', as: :clip_tag
  get 'leaderboard' => 'posts#leaderboard', as: :leaderboard
  root 'conversations#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	require 'open-uri'
	paginates_per 25

	has_many :posts, -> { order :created_at }, dependent: :destroy

	scope :feed, -> { joins(:posts).where("posts.created_at IN (SELECT MAX(posts.created_at) FROM posts WHERE posts.conversation_id = conversations.id)").order("posts.created_at DESC") }

	def responses
		user = posts.try(:first).try(:user)
		user ? posts.where.not(user: user).length : 0
	end

	def support_pages(q)
		search_url = "http://en.support.wordpress.com/?s=" + q
    return Nokogiri::HTML(open(search_url)).search("ul.dates > li").first(4)
	end

	def forum_pages(q)
		search_url = "http://en.forums.wordpress.com/search.php?q=" + q
    return Nokogiri::HTML(open(search_url)).search("ol.results > li").first(4)
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	STOP_WORDS = %W( a able add am and after again appear blog blogs by
		can cannot cant can't change changes changing com do does doesn't
		enter error first from for get had has have help home how
		i if in into is it keep make mine my need new not of on one only
		page please possible problem problems product products remove
		setting settings site sites someone that the these to today top
		want will with when why wont won't wordpress 1 2 3 4 5 6 7 8 9 10)

  belongs_to :conversation, touch: true
  belongs_to :user

  def self.get_conversations(page_number)
		forum_url = "http://en.forums.wordpress.com/"
		forum_url += "page/#{page_number}" unless page_number == 1
		puts forum_url

		forum = Nokogiri::HTML(open(forum_url))
		forum.search("tbody#latest tr").each do |row|
			conversation_title = row.search("td[1] a").text.to_s
			conversation_url = row.search("td[1] a @href").to_s
			conversation_count = row.search("td[2]").text.to_i
			@conversation = Conversation.find_or_create_by(url: conversation_url) do |f|
				f.title = conversation_title
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable

  def conversations
  	posts.map(&:conversation).uniq
  end

  def ppc
  	(posts.length.to_f / conversations.length).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @feed = Conversation.feed.page(params[:page])
  	@conversation = @feed.first
  	@posts = @conversation.posts
  end

  def show
  	@conversation = Conversation.find(params[:id])
  end

  def create_post
  	@conversation = Conversation.find(params[:id])

  	mechanize = Mechanize.new { |agent| agent.user_agent_alias = 'Mac Safari' }
  	@page = mechanize.get(@conversation.url) do |page|
  	  # Click the login link
  	  @login_page = mechanize.click(page.link_with(text: /log in/))

  	  # Submit the login form
  	  @post_page = @login_page.form_with(action: 'https://wordpress.com/wp-login.php') do |f|
  	  	f.log = ENV["wordpress_username"]
  	  	f.pwd = ENV["wordpress_password"]
  	  end.click_button

  	  # Submit the post
  	  @submit_page = @post_page.form_with(action: 'http://en.forums.wordpress.com/bb-post.php') do |f|
  	  	f.post_content = params[:body]
  	  end.click_button

      # Subscribe to conversation
      @subscribe_page = mechanize.click(@submit_page.link_with(text: /Subscribe to Topic/))
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def leaderboard
		@by_posts = User.select("users.*, count(posts.id) AS posts_count").preload(:posts).joins(:posts).group("users.id").order("posts_count DESC").first(20)
		@by_conversations = User.all.sort_by { |user| user.conversations.length }.reverse.first(20)
		@by_ppc = User.select {|user| user.posts.length > 40}.sort_by { |user| user.ppc }.first(20)
	end

	def clip_support_page
		@url = params[:url]
	end

	def clip_tag
		@tag = params[:tag]
	end

	def search
		@conversation = Conversation.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def item_class(conversation)
		string = ''
		string += 'active' if conversation == @conversation
		string += ' unanswered' if conversation.responses == 0
		string += ' he' if conversation.posts.map(&:user).include? User.find_by(username: "abreujamil")
		return string
	end

	def search_query(conversation)
		query = params[:q].present? ? params[:q] : conversation.title
		(query.downcase.parameterize.split("-") - Post::STOP_WORDS).join(" ").parameterize
	end
end

app/views/conversations/_conversation.html.slim
.middle-column
	.conversation
		.conversation-title
			= link_to conversation.url, target: "_blank" do
				span.mega-octicon.octicon-link-external
			= conversation.title
		.conversation-posts
			= render conversation.posts
		.conversation-form
			= form_tag create_post_path(conversation), method: "get", class: "new_post", remote: true do
				.legend
					- %w( a blockquote code em strong ul ol li ).each do |tag|
						= link_to clip_tag_path(tag: tag), remote: true do
							= tag
				= text_area_tag :body, nil, class: 'expanding', rows: 1
				= submit_tag "Search"
.right-column
	= render partial: "conversations/right_column", locals: { conversation: conversation }

app/views/conversations/_item.html.slim
.item id=(conversation.id) class=(item_class(conversation))
	= link_to conversation, remote: true do
		.item-count
			span= conversation.responses
		.item-title
			= conversation.title
			.item-timeago
				abbr.timeago title=(conversation.updated_at.to_time.iso8601)

app/views/conversations/_right_column.html.slim
.search-column
	= form_tag search_path(conversation), method: "get", class: "search", remote: true do
		= text_area_tag :q, nil, rows: 1
		= submit_tag "Search"

	- conversation.support_pages(search_query(conversation)).each do |page|
		.search-result
			- if page
				.search-result-clippy
					= link_to clip_support_page_path(url: page.search("a @href").to_s), remote: true do
						span.octicon.octicon-clippy
				.search-result-main
					= link_to page.search("a @href").to_s, target: "_blank" do
						= page.search("a").text
						.search-result-summary
							= page.search("div").text
	/ .search-title FORUM
	/ - conversation.forum_pages(search_query(conversation)).each do |page|
	/ 	.search-result
	/ 		- if page
	/ 			.search-result-clippy
	/ 				= link_to clip_support_page_path(url: page.search("a @href").to_s), remote: true do
	/ 					span.octicon.octicon-clippy
	/ 			.search-result-main
	/ 				= link_to page.search("a @href").to_s, target: "_blank" do
	/ 					= page.search("a").text
	/ 					.search-result-summary
	/ 						= page.search("p").text

app/views/conversations/create_post.js.erb
$(".conversation-posts").append("<a href=<%= @conversation.url %> target='_blank'><div class='notice'><span class='mega-octicon octicon-chevron-right'></span>Happiness Engineered!</div></a>");
$('.new_post')[0].reset();

app/views/conversations/index.html.slim
- content_for :javascript do
	= javascript_include_tag 'plugins/timeago', 'conversations/index'

.container
	.left-column
		.new-post-area
		= render partial: "item", collection: @feed, as: :conversation
		= paginate @feed, remote: true
	section
		= render @conversation

app/views/conversations/index.js.erb
$('nav.pagination').before('<%= j render partial: "item", collection: @feed, as: :conversation %>');
$('.pagination .next a').attr('href', '/conversations?page=<%= params[:page].to_i + 1 %>/');
$(".post a").attr("target", "_blank");
$("abbr.timeago").timeago();

app/views/conversations/show.js.erb
$("section").html("<%= j render @conversation %>");
$(".post a").attr("target", "_blank");
$(".item.active").toggleClass('active');
$("#<%= @conversation.id %>").toggleClass('active').removeClass('new');
$("textarea").expanding();

app/views/layouts/application.html.slim
doctype html
html
	head
		meta charset='utf-8'
		meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible'
		title HappyPress
		meta content='' name='description'
		meta content='width=device-width' name='viewport'
		= stylesheet_link_tag 'application', media: 'all'
		== yield :stylesheet
		= javascript_include_tag '//use.typekit.com/ier1ulg.js', "//js.pusher.com/2.2/pusher.min.js"
		= javascript_tag 'try{Typekit.load()}catch(e){}'
		= tag :meta, name: "pusher-key", content: ENV["pusher_key"]
		= csrf_meta_tags
	body
		.header
			= link_to root_path do
				.logo
				.text
					| HAPPY
					span PRESS
			.actions
				= link_to leaderboard_path do
					| Leaderboard
		== yield
		= javascript_include_tag 'application', 'plugins/expanding'
		== yield :javascript
		= debug(params) if Rails.env.development?

app/views/posts/_post.html.slim
.conversation-post class=('he' if post.user.title == "Happiness Engineer")
	.post-user
		.post-user-details
			.post-user-title
				= link_to post.user.title, post.user.profile_url, target: "_blank"
			span
				| //
			.post-created-at
				= link_to post.created_at.localtime.strftime("%b %e, %Y, %l:%M %p"), post.url, target: "_blank"
		.post-user-image
			= image_tag(post.user.image)
		.post-username
			= link_to post.user.username, post.user.blog_url, target: "_blank"
	.post-body
		= post.body.html_safe

app/views/posts/clip_support_page.js.erb
var textarea = $('textarea#body')
var current_text = textarea.val()
var new_text = current_text + "Hi! Here's a potentially useful link:\n\n<%= @url %>"

textarea.val(new_text)

app/views/posts/clip_tag.js.erb
var textarea = $('textarea#body')
var current_text = textarea.val()
var new_text = current_text + "<<%= @tag %>></<%= @tag %>>"

textarea.val(new_text)

app/views/posts/leaderboard.html.slim
.leaderboard
	.container
		.leaderboard-column
			.leaderboard-title Posts
			.leaderboard-subtitle
				= Post.all.length
			= render partial: "users/leaderboard_user", collection: @by_posts, as: :user, locals: { field: :posts }
		.leaderboard-column
			.leaderboard-title Conversations
			.leaderboard-subtitle= Conversation.all.length
			= render partial: "users/leaderboard_user", collection: @by_conversations, as: :user, locals: { field: :conversations }
		.leaderboard-column
			.leaderboard-title PPC
			.leaderboard-subtitle= (Post.all.length.to_f / Conversation.all.length).round(2)
			= render partial: "users/leaderboard_user", collection: @by_ppc, as: :user, locals: { field: :ppc }

app/views/posts/search.js.erb
$('.right-column').html('<%= j render partial: "conversations/right_column", locals: { conversation: @conversation } %>')

app/views/users/_leaderboard_user.html.slim
.leaderboard-user class=(user.title == "Member" ? nil : 'el')
	.leaderboard-count
		span
			- if field == :posts
				= user.posts.length
			- elsif field == :conversations
				= user.conversations.length
			- elsif field == :ppc
				= user.ppc.round(2)
	.leaderboard-user-image
		= image_tag user.image
	.leaderboard-username
		= user.username
		div
			= user.title